name: Build Simple APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Install dependencies
      run: npm install --legacy-peer-deps
      
    - name: Complete Android configuration without React Native dependencies
      run: |
        cd android
        
        # Set Gradle version
        echo "distributionUrl=https\\://services.gradle.org/distributions/gradle-7.6.3-bin.zip" > gradle/wrapper/gradle-wrapper.properties
        
        # Create root build.gradle
        cat > build.gradle << 'EOF'
        buildscript {
            ext {
                buildToolsVersion = "33.0.0"
                minSdkVersion = 21
                compileSdkVersion = 33
                targetSdkVersion = 33
            }
            repositories {
                google()
                mavenCentral()
            }
            dependencies {
                classpath("com.android.tools.build:gradle:7.4.2")
            }
        }
        
        allprojects {
            repositories {
                google()
                mavenCentral()
            }
        }
        EOF
        
        # Create minimal app build.gradle
        cat > app/build.gradle << 'EOF'
        apply plugin: "com.android.application"
        
        android {
            namespace "com.timerapp"
            compileSdkVersion 33
            buildToolsVersion "33.0.0"
            
            defaultConfig {
                applicationId "com.timerapp"
                minSdkVersion 21
                targetSdkVersion 33
                versionCode 1
                versionName "1.0"
            }
            
            buildTypes {
                release {
                    minifyEnabled false
                }
            }
        }
        
        dependencies {
            implementation "androidx.core:core-ktx:1.9.0"
            implementation "androidx.appcompat:appcompat:1.6.1"
        }
        EOF
        
        # Create settings.gradle
        echo "include ':app'" > settings.gradle
        echo "rootProject.name = 'TimerApp'" >> settings.gradle
        
    - name: Build APK
      run: |
        cd android
        chmod +x gradlew
        ./gradlew clean assembleRelease --no-daemon
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: android/app/build/outputs/apk/release/app-release.apk
