name: Build React Native APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Install dependencies
      run: npm install --legacy-peer-deps
        
    - name: Complete Android configuration
      run: |
        cd android
        
        # Set Gradle version
        echo "distributionUrl=https\\://services.gradle.org/distributions/gradle-7.6.3-bin.zip" > gradle/wrapper/gradle-wrapper.properties
        
        # Create root build.gradle
        cat > build.gradle << 'EOF'
        buildscript {
            ext {
                buildToolsVersion = "33.0.0"
                minSdkVersion = 21
                compileSdkVersion = 33
                targetSdkVersion = 33
            }
            repositories {
                google()
                mavenCentral()
            }
            dependencies {
                classpath("com.android.tools.build:gradle:7.4.2")
            }
        }
        
        allprojects {
            repositories {
                google()
                mavenCentral()
            }
        }
        EOF
        
        # Create app build.gradle
        cat > app/build.gradle << 'EOF'
        apply plugin: "com.android.application"
        
        android {
            namespace "com.timerapp"
            compileSdkVersion 33
            buildToolsVersion "33.0.0"
            
            defaultConfig {
                applicationId "com.timerapp"
                minSdkVersion 21
                targetSdkVersion 33
                versionCode 1
                versionName "1.0"
            }
            
            buildTypes {
                release {
                    minifyEnabled false
                }
            }
            
            lint {
                checkReleaseBuilds false
                abortOnError false
            }
        }
        
        dependencies {
            implementation "androidx.core:core-ktx:1.9.0"
            implementation "androidx.appcompat:appcompat:1.6.1"
        }
        EOF
        
        # Create settings.gradle
        echo "include ':app'" > settings.gradle
        echo "rootProject.name = 'TimerApp'" >> settings.gradle
        
    - name: Make gradlew executable
      run: chmod +x ./android/gradlew
      
    - name: Build APK
      run: |
        cd android
        ./gradlew clean
        ./gradlew assembleRelease --no-daemon --stacktrace
        
    - name: Debug - List all build outputs
      run: |
        cd android
        echo "=== Searching for APK files ==="
        find . -name "*.apk" -type f -exec ls -la {} \;
        echo "=== Build outputs directory structure ==="
        find app/build -type d -name "*apk*" || echo "No APK directories found"
        echo "=== All files in build/outputs ==="
        find app/build/outputs -type f || echo "No outputs directory found"
        
    - name: Upload APK (Multiple Paths)
      uses: actions/upload-artifact@v4
      with:
        name: TimerApp-APK
        path: |
          android/app/build/outputs/apk/release/*.apk
          android/app/build/outputs/apk/**/*.apk
          android/app/build/outputs/**/*.apk
        if-no-files-found: error
